username = input ('Введите имя пользователя:')
title = input ('Введите заголовок заметки:')
content = input ('Описание заметки:')
status = input ('Статус заметки:')
created_date = input ('Дата создания заметки в формате (день-месяц-год):')
issue_date = input('Дедлайн в формате (день-месяц-год):')
print(username)
print(title)
print(content)
print(status)
print(created_date[0:5])
print(issue_date[0:5])
